/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:9c0129c7-80a9-4c42-b49c-f29ac348251a",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_bkcwnqF7K",
    "aws_user_pools_web_client_id": "4jv1hrm6s5o3m6cvhfdik4hral",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "ADDRESS",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "productstable-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "cartstable-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "orderstable-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_user_files_s3_bucket": "amplifys3storageproducts102424-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "productsapi",
            "endpoint": "https://x92il36x93.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        },
        {
            "name": "cartsapi",
            "endpoint": "https://36xzcr71r8.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        },
        {
            "name": "ordersapi",
            "endpoint": "https://1ad55hhs4k.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
